---
title: "Lab 02 - Plastic waste"
author: "Jude Sullivan"
date: "January 27, 2022"
output: html_document
---

## Load packages and data

```{r setup, message=FALSE}
# Load the tidyverse package

library(tidyverse)
```

```{r load-data, message=FALSE}

#install.packages("here")

plastic_waste <- read.csv(here::here("data/plastic-waste.csv"))

```

## Exercises

### Exercise 1


```{r plastic-waste-continent}

#histograms by continent 

ggplot(data = plastic_waste) +
  aes(x = plastic_waste_per_cap,
      color = continent) +
  geom_histogram(binwidth = 0.2)

```

```{r plastic-waste-continent; density}

#density by continent

ggplot(data = plastic_waste) +
  aes(x = plastic_waste_per_cap,
      color = continent) +
  geom_density(binwidth = 0.2) 

```

```{r plastic-waste-continent; histogram & density}

#histogram & density by continent 

ggplot(data = plastic_waste) +
  aes(x = plastic_waste_per_cap,
      color = continent) +
  geom_density(aes(y = after_stat(count)), binwidth = 0.2) 

```

```{r plastic-waste-continent; density colored}

#colored density by continent 

ggplot(data = plastic_waste) +
  aes(x = plastic_waste_per_cap,
      fill =  continent,
      color = continent) +
  geom_density(binwidth = 0.2) 


#add alpha!!!!!!!!!

```

### Exercise 2

```{r plastic-waste-density; boxplot }

ggplot(data = plastic_waste) +
  aes(x = plastic_waste_per_cap,
      fill =  continent,
      color = continent) +
  geom_boxplot(binwidth = 0.2) 

```

```{r plastic-waste-density; raincloud}

#install.packages("ggdist")

ggplot(data = plastic_waste) +
  aes(y = continent,
      x = plastic_waste_per_cap,
      fill = continent,
      color = continent) +
  geom_jitter(height = .15) +
  geom_boxplot(color = "black",
               alpha = .5,
               width = .1,
               size = .5) +
  ggdist::stat_slab(height = .3,
                    color = "black",
                    size = .2,
                    alpha = .5,
                    position = position_nudge(y = .2))

```

### Exercise 3

```{r plastic-waste-density; scatterplot}

ggplot(data = plastic_waste) +
  aes(y = plastic_waste_per_cap,
      x = mismanaged_plastic_waste_per_cap,
      fill = continent,
      color = continent,
      shape = continent) +
  geom_point()

```

```{r plastic-waste-density; scatterplot w/ population}

#plastic_waste_per_cap x total_pop 

ggplot(data = plastic_waste) +
  aes(y = plastic_waste_per_cap,
      x = total_pop,
      fill = continent,
      color = continent,
      shape = continent) +
  geom_point()

#plastic_waste_per_cap x coastal_pop

ggplot(data = plastic_waste) +
  aes(y = plastic_waste_per_cap,
      x = coastal_pop,
      fill = continent,
      color = continent,
      shape = continent) +
  geom_point()


```

