---
title: "Lab 7"
author: "Jude Sullivan"
date: "5/1/2022"
output: html_document
---
```{r intro, include=FALSE}

# For this lab, I am revisiting Lab 3 and fancying up the plots following the later lectures about ggplot!
# Exercises 1.1-1.4 did not involve plotting, so I removed these sections from this lab.
# The bonus exercise in Lab 3 did not involve plotting, so I removed this section from this lab activity.

```


```{r setup, include=FALSE}
# I orginally only loaded the tidyverse and gapminder packages, but I have also loaded the ggforce and ggthemes packages for this lab in order to customize my plots!

library(tidyverse)
library(gapminder)
library(ggforce)
library(ggthemes)

```


# Exercise 1


## 1.5

```{r scatterplot, canada, lifeexp, gdp}
#For the following two Canadian plots, I added titles and changed the color of the lines!

gapminder |> 
  filter(country %in% "Canada")

canada <- filter(gapminder, country %in% "Canada")


#without log

ggplot(canada) + 
aes(x = gdpPercap, y = lifeExp) +
  geom_point() +
  geom_smooth(color = "darkgreen") +
  labs(title = "Life Expectancy in Canada from 1952-2007 by Gross 
                   Domestic Product per Capita")

#with log

ggplot(canada) + 
aes(x = gdpPercap, y = lifeExp) +
  geom_point() + 
  scale_x_log10() +
  geom_smooth(color = "darkred") +
  labs(title = "Life Expectancy in Canada from 1952-2007 by Gross 
           Domestic Product per Capita (log scale)")

```

# Exercise 2

```{r ex2}
datasets::iris

tibble(iris)

iris_tbl <- as_tibble(iris)

knitr::kable(iris_tbl)

```

## 2.1

```{r summary, scatterplot}
#Here, I added a title to the plot and used the economist theme!

summarize(iris, mean(Sepal.Length), sd(Sepal.Length), range(Sepal.Length), 
          mean(Petal.Length), sd(Petal.Length), range(Petal.Length))

ggplot(iris) +
  aes(x = Sepal.Length, y = Petal.Length) +
  geom_point() +
  labs(title = "Iris Sepal and Petal Lengths") +
  theme_economist()

```

## 2.2

```{r summary, scatterplot, categorical}
#Here, I added colored the plot by species, added a title, and then used a new theme that mimics the defaults of LibreOffice Calc graphs.

iris |> 
  group_by(Species) |> 
  summarize(n(),mean(Sepal.Length), sd(Sepal.Length), range(Sepal.Length))

ggplot(iris) +
  aes(x = Species, y = Sepal.Length, color = Species) +
  geom_point() +
  labs(title = "Iris Sepal Lengths by Species") +
  theme_calc() +
  scale_color_calc()


# Here is an updated boxplot with a title and customized colors!
# Inspired by https://t-redactyl.io/blog/2016/04/creating-plots-in-r-using-ggplot2-part-10-boxplots.html

ggplot(iris) +
  aes(y = Sepal.Length,
      x = Species) +
  geom_boxplot(fill =  "#4271AE", colour = "#1F3552")  +
  labs(title = "Iris Sepal Lengths by Species") +
  theme_bw()


# Finally, I added a title and the newer Excel theme to this raincloud plot

ggplot(iris) +
  aes(y = Species,
      x = Sepal.Length,
      fill = Species,
      color = Species) +
  geom_jitter(height = .15) +
  geom_boxplot(color = "black",
               alpha = .5,
               width = .1,
               size = .5) +
  ggdist::stat_slab(height = .3,
                    color = "black",
                    size = .2,
                    alpha = .5,
                    position = position_nudge(y = .2)) +
  labs(title = "Density and Distribution of Iris Sepal Length 
       by Species") +
  theme_excel_new() +
  scale_color_excel_new() +
  scale_fill_excel_new()

```

